In [7]:
import os
import sys
import json
import uuid
import datetime
import pandas as pd
from pathlib import Path

In [8]:
cwd = Path.cwd()
project_root = cwd.parent

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))
    print("Done!")

In [22]:
from credit_risk.monitoring.prediction_logger import log_predictions
from credit_risk.api.schemas import RequestModel

In [23]:
uid = str(uuid.uuid4())
uid

'b901e443-ff6d-4f72-a441-e485bdaf47bc'

In [24]:
pred = 1
prob = 0.73
reason_codes = {
    "dti": 0.42,
    "fico_range_low": -0.31,
    "revol_util": 0.18,
    "annual_inc": -0.15,
    "term": 0.09
}

In [25]:
with open(project_root / "test_payload.json", 'r') as f:
    raw_input = json.load(f)

In [26]:
req = RequestModel(**raw_input)

In [27]:
issue_d = datetime.date.today()
issue_d

datetime.date(2026, 8, 16)

In [10]:
log_predictions(
    issue_d=issue_d,
    req=req,
    req_id=uid,
    pred=pred,
    prob=prob,
    reason_codes=reason_codes
)

2026-08-15 20:34:29.205 | INFO     | credit_risk.monitoring.prediction_logger:log_predictions:92 - Query executed successfully

In [16]:
# checking if this it got added in the database
from dotenv import load_dotenv

load_dotenv()

True

In [2]:
import psycopg2

In [ ]:
import os
import pandas as pd
verify_conn_str = ""

conn = psycopg2.connect(verify_conn_str)

sql = """
    SELECT * FROM prediction_logs
"""

df = pd.read_sql("SELECT * FROM prediction_logs ORDER BY logged_at DESC LIMIT 1", conn)

In [20]:
df

,id,request_id,logged_at,issue_d,loan_amnt,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,...,term,emp_length,home_ownership,verification_status,purpose,addr_state,initial_list_status,pred,prob,reason_codes
0,1,a297bcc0-7fd6-4dd3-87af-525b604c6f7b,2026-08-15 14:02:04.346050,2026-08-15,10000.0,310.0,120000.0,8.5,0.0,0.0,...,36 months,10+ years,MORTGAGE,Verified,credit_card,CA,w,1,0.73,"{'dti': 0.42, 'term': 0.09, 'annual_inc': -0.1..."

In [1]:
import time

t0 = time.time()
from credit_risk.monitoring.prediction_logger import pool
print("import + pool creation took:", time.time() - t0)

t0 = time.time()
conn = pool.getconn()
print("getconn took:", time.time() - t0)

cur = conn.cursor()
t0 = time.time()
cur.execute("SELECT 1")
print("query took:", time.time() - t0)

cur.close()
pool.putconn(conn)

2026-08-15 20:33:03.771 | INFO     | credit_risk.config:<module>:11 - PROJ_ROOT path is: /Users/ak007/SML/Credit-Risk-Default-Prediction-System

import + pool creation took: 2.7973692417144775
getconn took: 4.7206878662109375e-05
query took: 0.7439389228820801

In [20]:
conn_str = os.getenv("MONITORING_READER_DB_URI")
conn = psycopg2.connect(conn_str)

df = pd.read_sql("SELECT * FROM prediction_logs LIMIT 1;", conn)

conn.close()
df

/var/folders/69/dxynlnqj6413x3bgy4c63zhc0000gn/T/ipykernel_54906/845238542.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM prediction_logs LIMIT 1;", conn)

,id,request_id,logged_at,issue_d,loan_amnt,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,...,term,emp_length,home_ownership,verification_status,purpose,addr_state,initial_list_status,pred,prob,reason_codes
0,1,a297bcc0-7fd6-4dd3-87af-525b604c6f7b,2026-08-15 14:02:04.346050,2026-08-15,10000.0,310.0,120000.0,8.5,0.0,0.0,...,36 months,10+ years,MORTGAGE,Verified,credit_card,CA,w,1,0.73,"{'dti': 0.42, 'term': 0.09, 'annual_inc': -0.1..."

In [28]:
conn_str = os.getenv("MONITORING_READER_DB_URI")
conn = psycopg2.connect(conn_str)
cur = conn.cursor()

cur.execute("INSERT INTO prediction_logs (request_id) VALUES ('00000000-0000-0000-0000-000000000000');")
conn.commit()

cur.close()
conn.close()

InsufficientPrivilege: permission denied for table prediction_logs

In [4]:
from credit_risk.dataset import AFTER_EDA, load_splits
from credit_risk.monitoring.log_loader import load_prediction_logs
from credit_risk.monitoring.psi import build_drift_report

2026-08-16 17:46:29.271 | INFO     | credit_risk.config:<module>:13 - PROJ_ROOT path is: /Users/ak007/SML/Credit-Risk-Default-Prediction-System

In [5]:
train_df, _, _, _ = load_splits(path=AFTER_EDA)
live_df = load_prediction_logs()

report = build_drift_report(reference_df=train_df, target_df=live_df, target_label='live')
report

2026-08-16 17:46:31.859 | INFO     | credit_risk.dataset:load_splits:261 | req_id=- - Checking if the files exists...
2026-08-16 17:46:31.867 | INFO     | credit_risk.dataset:load_splits:263 | req_id=- - Loading the Cached files...
2026-08-16 17:46:32.308 | INFO     | credit_risk.dataset:load_splits:271 | req_id=- - Loaded sucessfully all the splits and the metadata, Train_df shape: (466042, 110), val_df shape: (420204, 110), test_df shape: (431712, 110)
2026-08-16 17:46:32.333 | INFO     | credit_risk.monitoring.log_loader:load_prediction_logs:18 | req_id=- - Starting to load the prediction logs from prediction_logs table...
2026-08-16 17:46:32.333 | INFO     | credit_risk.monitoring.log_loader:load_prediction_logs:21 | req_id=- - Connecting to the DB...
2026-08-16 17:47:51.045 | INFO     | credit_risk.monitoring.log_loader:load_prediction_logs:23 | req_id=- - Connection Successfull!
2026-08-16 17:47:51.047 | INFO     | credit_risk.monitoring.log_loader:load_prediction_logs:26 | req_id=- - Trying to read the logs...

/Users/ak007/SML/Credit-Risk-Default-Prediction-System/credit_risk/monitoring/log_loader.py:27: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM prediction_logs", conn)

2026-08-16 17:48:00.075 | INFO     | credit_risk.monitoring.log_loader:load_prediction_logs:32 | req_id=- - Read the logs successfully!
2026-08-16 17:48:00.076 | INFO     | credit_risk.monitoring.log_loader:load_prediction_logs:37 | req_id=- - Adding the target place holder...
2026-08-16 17:48:00.076 | INFO     | credit_risk.monitoring.log_loader:load_prediction_logs:41 | req_id=- - Correcting the Date dtype features...
2026-08-16 17:48:00.079 | INFO     | credit_risk.monitoring.log_loader:load_prediction_logs:45 | req_id=- - Correcting the potential null features dtypes...
2026-08-16 17:48:00.080 | INFO     | credit_risk.monitoring.psi:build_drift_report:154 | req_id=- - [build_drift_report] target_label='live': processing 58 numeric + 7 categorical features
2026-08-16 17:48:00.080 | INFO     | credit_risk.features:prep_one_split:214 | req_id=- - Inside Function: prep_one_split
2026-08-16 17:48:00.080 | INFO     | credit_risk.features:sorting_with_issue_d:140 | req_id=- - Sorting the dataframe wrt to issue_d...
2026-08-16 17:48:00.286 | INFO     | credit_risk.features:sorting_with_issue_d:145 | req_id=- - Sorted successfully!
2026-08-16 17:48:00.286 | INFO     | credit_risk.features:split_target_and_features:150 | req_id=- - Inside Function: split_target_and_features
2026-08-16 17:48:00.286 | INFO     | credit_risk.features:split_target_and_features:151 | req_id=- - Splitting the target and the features...
2026-08-16 17:48:00.362 | INFO     | credit_risk.features:split_target_and_features:154 | req_id=- - features and target are splitted successfully...
2026-08-16 17:48:00.362 | INFO     | credit_risk.features:add_credit_yrs:167 | req_id=- - Inside Function: add_credit_yrs
2026-08-16 17:48:00.362 | INFO     | credit_risk.features:add_credit_yrs:169 | req_id=- - Adding the feature 'credit_yrs'
2026-08-16 17:48:00.366 | INFO     | credit_risk.features:add_credit_yrs:171 | req_id=- - 'credit_age_yrs added successfully!'
2026-08-16 17:48:00.366 | INFO     | credit_risk.features:add_fico_mid:176 | req_id=- - Inside Function: add_fico_mid
2026-08-16 17:48:00.366 | INFO     | credit_risk.features:add_fico_mid:178 | req_id=- - Adding the feature 'fico_mid'
2026-08-16 17:48:00.367 | INFO     | credit_risk.features:add_fico_mid:180 | req_id=- - 'fico_mid' added successfully!
2026-08-16 17:48:00.367 | INFO     | credit_risk.features:drop_columns:159 | req_id=- - Inside Function: drop_columns
2026-08-16 17:48:00.367 | INFO     | credit_risk.features:drop_columns:160 | req_id=- - Drpping columns given un the DROP_COLS
2026-08-16 17:48:00.409 | INFO     | credit_risk.features:drop_columns:162 | req_id=- - Dropped successfully!
2026-08-16 17:48:00.427 | INFO     | credit_risk.features:prep_one_split:214 | req_id=- - Inside Function: prep_one_split
2026-08-16 17:48:00.427 | INFO     | credit_risk.features:sorting_with_issue_d:140 | req_id=- - Sorting the dataframe wrt to issue_d...
2026-08-16 17:48:00.428 | INFO     | credit_risk.features:sorting_with_issue_d:145 | req_id=- - Sorted successfully!
2026-08-16 17:48:00.428 | INFO     | credit_risk.features:split_target_and_features:150 | req_id=- - Inside Function: split_target_and_features
2026-08-16 17:48:00.428 | INFO     | credit_risk.features:split_target_and_features:151 | req_id=- - Splitting the target and the features...
2026-08-16 17:48:00.428 | INFO     | credit_risk.features:split_target_and_features:154 | req_id=- - features and target are splitted successfully...
2026-08-16 17:48:00.428 | INFO     | credit_risk.features:add_credit_yrs:167 | req_id=- - Inside Function: add_credit_yrs
2026-08-16 17:48:00.428 | INFO     | credit_risk.features:add_credit_yrs:169 | req_id=- - Adding the feature 'credit_yrs'
2026-08-16 17:48:00.428 | INFO     | credit_risk.features:add_credit_yrs:171 | req_id=- - 'credit_age_yrs added successfully!'
2026-08-16 17:48:00.428 | INFO     | credit_risk.features:add_fico_mid:176 | req_id=- - Inside Function: add_fico_mid
2026-08-16 17:48:00.429 | INFO     | credit_risk.features:add_fico_mid:178 | req_id=- - Adding the feature 'fico_mid'
2026-08-16 17:48:00.429 | INFO     | credit_risk.features:add_fico_mid:180 | req_id=- - 'fico_mid' added successfully!
2026-08-16 17:48:00.429 | INFO     | credit_risk.features:drop_columns:159 | req_id=- - Inside Function: drop_columns
2026-08-16 17:48:00.429 | INFO     | credit_risk.features:drop_columns:160 | req_id=- - Drpping columns given un the DROP_COLS
2026-08-16 17:48:00.429 | INFO     | credit_risk.features:drop_columns:162 | req_id=- - Dropped successfully!
2026-08-16 17:48:00.429 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'loan_amnt' with 10 requested bins
2026-08-16 17:48:00.453 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'loan_amnt': PSI = 0.0152
2026-08-16 17:48:00.453 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'installment' with 10 requested bins
2026-08-16 17:48:00.471 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'installment': PSI = 0.0250
2026-08-16 17:48:00.471 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'annual_inc' with 10 requested bins
2026-08-16 17:48:00.488 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'annual_inc': PSI = 0.0059
2026-08-16 17:48:00.488 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'dti' with 10 requested bins
2026-08-16 17:48:00.506 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'dti': PSI = 0.1132
2026-08-16 17:48:00.506 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'delinq_2yrs' with 10 requested bins
2026-08-16 17:48:00.512 | INFO     | credit_risk.monitoring.psi:psi_numeric:40 | req_id=- - [psi_numeric] 'delinq_2yrs': duplicate bin edges collapsed 10 requested bins down to 3 actual bins
2026-08-16 17:48:00.513 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'delinq_2yrs': PSI = 0.0114
2026-08-16 17:48:00.513 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'inq_last_6mths' with 10 requested bins
2026-08-16 17:48:00.522 | INFO     | credit_risk.monitoring.psi:psi_numeric:40 | req_id=- - [psi_numeric] 'inq_last_6mths': duplicate bin edges collapsed 10 requested bins down to 4 actual bins
2026-08-16 17:48:00.523 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'inq_last_6mths': PSI = 0.1153
2026-08-16 17:48:00.523 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'mths_since_last_delinq' with 10 requested bins
2026-08-16 17:48:00.541 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'mths_since_last_delinq': PSI = 0.0284
2026-08-16 17:48:00.541 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'mths_since_last_record' with 10 requested bins
2026-08-16 17:48:00.553 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'mths_since_last_record': PSI = 0.0623
2026-08-16 17:48:00.553 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'open_acc' with 10 requested bins
2026-08-16 17:48:00.568 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'open_acc': PSI = 0.0245
2026-08-16 17:48:00.568 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'pub_rec' with 10 requested bins
2026-08-16 17:48:00.574 | INFO     | credit_risk.monitoring.psi:psi_numeric:40 | req_id=- - [psi_numeric] 'pub_rec': duplicate bin edges collapsed 10 requested bins down to 3 actual bins
2026-08-16 17:48:00.576 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'pub_rec': PSI = 0.0232
2026-08-16 17:48:00.576 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'revol_bal' with 10 requested bins
2026-08-16 17:48:00.593 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'revol_bal': PSI = 0.0143
2026-08-16 17:48:00.593 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'revol_util' with 10 requested bins
2026-08-16 17:48:00.610 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'revol_util': PSI = 0.0690
2026-08-16 17:48:00.611 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'total_acc' with 10 requested bins
2026-08-16 17:48:00.627 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'total_acc': PSI = 0.0032
2026-08-16 17:48:00.627 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'collections_12_mths_ex_med' with 10 requested bins
2026-08-16 17:48:00.632 | INFO     | credit_risk.monitoring.psi:psi_numeric:40 | req_id=- - [psi_numeric] 'collections_12_mths_ex_med': duplicate bin edges collapsed 10 requested bins down to 2 actual bins
2026-08-16 17:48:00.633 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'collections_12_mths_ex_med': PSI = 0.0079
2026-08-16 17:48:00.633 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'mths_since_last_major_derog' with 10 requested bins
2026-08-16 17:48:00.647 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'mths_since_last_major_derog': PSI = 0.0368
2026-08-16 17:48:00.647 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'acc_now_delinq' with 10 requested bins
2026-08-16 17:48:00.652 | INFO     | credit_risk.monitoring.psi:psi_numeric:40 | req_id=- - [psi_numeric] 'acc_now_delinq': duplicate bin edges collapsed 10 requested bins down to 2 actual bins
2026-08-16 17:48:00.653 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'acc_now_delinq': PSI = 0.0010
2026-08-16 17:48:00.653 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'tot_coll_amt' with 10 requested bins
2026-08-16 17:48:00.660 | INFO     | credit_risk.monitoring.psi:psi_numeric:40 | req_id=- - [psi_numeric] 'tot_coll_amt': duplicate bin edges collapsed 10 requested bins down to 3 actual bins
2026-08-16 17:48:00.661 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'tot_coll_amt': PSI = 1.1517
2026-08-16 17:48:00.661 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'tot_cur_bal' with 10 requested bins
2026-08-16 17:48:00.676 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'tot_cur_bal': PSI = 1.1497
2026-08-16 17:48:00.677 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'total_rev_hi_lim' with 10 requested bins
2026-08-16 17:48:00.692 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'total_rev_hi_lim': PSI = 1.1386
2026-08-16 17:48:00.692 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'acc_open_past_24mths' with 10 requested bins
2026-08-16 17:48:00.705 | INFO     | credit_risk.monitoring.psi:psi_numeric:40 | req_id=- - [psi_numeric] 'acc_open_past_24mths': duplicate bin edges collapsed 10 requested bins down to 8 actual bins
2026-08-16 17:48:00.706 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'acc_open_past_24mths': PSI = 0.8008
2026-08-16 17:48:00.706 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'avg_cur_bal' with 10 requested bins
2026-08-16 17:48:00.722 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'avg_cur_bal': PSI = 1.1387
2026-08-16 17:48:00.722 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'bc_open_to_buy' with 10 requested bins
2026-08-16 17:48:00.739 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'bc_open_to_buy': PSI = 0.8662
2026-08-16 17:48:00.739 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'bc_util' with 10 requested bins
2026-08-16 17:48:00.755 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'bc_util': PSI = 0.9035
2026-08-16 17:48:00.755 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'chargeoff_within_12_mths' with 10 requested bins
2026-08-16 17:48:00.760 | INFO     | credit_risk.monitoring.psi:psi_numeric:40 | req_id=- - [psi_numeric] 'chargeoff_within_12_mths': duplicate bin edges collapsed 10 requested bins down to 2 actual bins
2026-08-16 17:48:00.762 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'chargeoff_within_12_mths': PSI = 0.0001
2026-08-16 17:48:00.762 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'delinq_amnt' with 10 requested bins
2026-08-16 17:48:00.766 | INFO     | credit_risk.monitoring.psi:psi_numeric:40 | req_id=- - [psi_numeric] 'delinq_amnt': duplicate bin edges collapsed 10 requested bins down to 2 actual bins
2026-08-16 17:48:00.768 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'delinq_amnt': PSI = 0.0009
2026-08-16 17:48:00.768 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'mo_sin_old_il_acct' with 10 requested bins
2026-08-16 17:48:00.784 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'mo_sin_old_il_acct': PSI = 1.4064
2026-08-16 17:48:00.784 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'mo_sin_old_rev_tl_op' with 10 requested bins
2026-08-16 17:48:00.800 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'mo_sin_old_rev_tl_op': PSI = 1.1528
2026-08-16 17:48:00.800 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'mo_sin_rcnt_rev_tl_op' with 10 requested bins
2026-08-16 17:48:00.815 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'mo_sin_rcnt_rev_tl_op': PSI = 1.1325
2026-08-16 17:48:00.815 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'mo_sin_rcnt_tl' with 10 requested bins
2026-08-16 17:48:00.828 | INFO     | credit_risk.monitoring.psi:psi_numeric:40 | req_id=- - [psi_numeric] 'mo_sin_rcnt_tl': duplicate bin edges collapsed 10 requested bins down to 9 actual bins
2026-08-16 17:48:00.830 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'mo_sin_rcnt_tl': PSI = 1.1331
2026-08-16 17:48:00.830 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'mort_acc' with 10 requested bins
2026-08-16 17:48:00.841 | INFO     | credit_risk.monitoring.psi:psi_numeric:40 | req_id=- - [psi_numeric] 'mort_acc': duplicate bin edges collapsed 10 requested bins down to 7 actual bins
2026-08-16 17:48:00.842 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'mort_acc': PSI = 0.7964
2026-08-16 17:48:00.842 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'mths_since_recent_bc' with 10 requested bins
2026-08-16 17:48:00.858 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'mths_since_recent_bc': PSI = 0.8298
2026-08-16 17:48:00.858 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'mths_since_recent_bc_dlq' with 10 requested bins
2026-08-16 17:48:00.872 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'mths_since_recent_bc_dlq': PSI = 0.0205
2026-08-16 17:48:00.872 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'mths_since_recent_inq' with 10 requested bins
2026-08-16 17:48:00.888 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'mths_since_recent_inq': PSI = 0.0697
2026-08-16 17:48:00.888 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'mths_since_recent_revol_delinq' with 10 requested bins
2026-08-16 17:48:00.903 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'mths_since_recent_revol_delinq': PSI = 0.0283
2026-08-16 17:48:00.903 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'num_accts_ever_120_pd' with 10 requested bins
2026-08-16 17:48:00.910 | INFO     | credit_risk.monitoring.psi:psi_numeric:40 | req_id=- - [psi_numeric] 'num_accts_ever_120_pd': duplicate bin edges collapsed 10 requested bins down to 3 actual bins
2026-08-16 17:48:00.912 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'num_accts_ever_120_pd': PSI = 1.1415
2026-08-16 17:48:00.912 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'num_actv_bc_tl' with 10 requested bins
2026-08-16 17:48:00.923 | INFO     | credit_risk.monitoring.psi:psi_numeric:40 | req_id=- - [psi_numeric] 'num_actv_bc_tl': duplicate bin edges collapsed 10 requested bins down to 7 actual bins
2026-08-16 17:48:00.925 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'num_actv_bc_tl': PSI = 1.1387
2026-08-16 17:48:00.925 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'num_actv_rev_tl' with 10 requested bins
2026-08-16 17:48:00.938 | INFO     | credit_risk.monitoring.psi:psi_numeric:40 | req_id=- - [psi_numeric] 'num_actv_rev_tl': duplicate bin edges collapsed 10 requested bins down to 9 actual bins
2026-08-16 17:48:00.939 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'num_actv_rev_tl': PSI = 1.1478
2026-08-16 17:48:00.939 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'num_bc_sats' with 10 requested bins
2026-08-16 17:48:00.951 | INFO     | credit_risk.monitoring.psi:psi_numeric:40 | req_id=- - [psi_numeric] 'num_bc_sats': duplicate bin edges collapsed 10 requested bins down to 7 actual bins
2026-08-16 17:48:00.952 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'num_bc_sats': PSI = 0.9256
2026-08-16 17:48:00.952 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'num_bc_tl' with 10 requested bins
2026-08-16 17:48:00.967 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'num_bc_tl': PSI = 1.2009
2026-08-16 17:48:00.967 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'num_il_tl' with 10 requested bins
2026-08-16 17:48:00.982 | INFO     | credit_risk.monitoring.psi:psi_numeric:68 | req_id=- - [psi_numeric] 'num_il_tl': PSI = 1.1449
2026-08-16 17:48:00.982 | INFO     | credit_risk.monitoring.psi:psi_numeric:27 | req_id=- - [psi_numeric] Calculating PSI for 'num_op_rev_tl' with 10 requested bins

                feature       PSI  drift_level target_label
0             loan_amnt  0.015190       stable         live
1           installment  0.024982       stable         live
2            annual_inc  0.005923       stable         live
3                   dti  0.113166     moderate         live
4           delinq_2yrs  0.011361       stable         live
..                  ...       ...          ...          ...
60       home_ownership  0.005441       stable         live
61  verification_status  0.078367       stable         live
62              purpose  0.050574       stable         live
63           addr_state  0.114496     moderate         live
64  initial_list_status  0.757319  significant         live

[65 rows x 4 columns]

In [ ]:
from locustfile import row_to_payload

RuntimeError: cannot release un-acquired lock

ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/ak007/SML/Credit-Risk-Default-Prediction-System/.venv/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 550, in _run_callback
    f = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ak007/SML/Credit-Risk-Default-Prediction-System/.venv/lib/python3.11/site-packages/ipykernel/subshell_manager.py", line 227, in _send_on_shell_channel
    assert current_thread().name == SHELL_CHANNEL_THREAD_NAME
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/Users/ak007/SML/Credit-Risk-Default-Prediction-System/.venv/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 600, in _handle_events
    self._handle_recv()
  File "/Users/ak007/SML/Credit-Risk-Default-Prediction-System/.venv/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 629, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/ak007/SML/Credit-Risk-Default-Prediction-System/.venv/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 550, in _run_callback
    f = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ak007/SML/Credit-Risk-Default-Prediction-System/.venv/lib/python3.11/site-packages/ipykernel/subshell_manager.py", line 227, in _send_on_shell_channel
    assert current_thread().name == SHELL_CHANNEL_THREAD_NAME
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Exception in callback BaseAsyncIOLoop._handle_events(81, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(81, 1)>
Traceback (most recent call last):
  File "/Users/ak007/.local/share/uv/python/cpython-3.11.15-macos-aarch64-none/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/ak007/SML/Credit-Risk-Default-Prediction-System/.venv/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 208, in _handle_events
    handler_func(fileobj, events)
  File "/Users/ak007/SML/Credit-Risk-Default-Prediction-System/.venv/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 600, in _handle_events
    self._handle_recv()
  File "/Users/ak007/SML/Credit-Risk-Default-Prediction-System/.venv/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 629, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/ak007/SML/Credit-Risk-Default-Prediction-System/.venv/lib/python3.11/site-packages/zmq/eventloop/zmqstream.py", line 550, in _run_callback
    f = callback(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ak007/SML/Credit-Risk-Default-Prediction-System/.venv/lib/python3.11/site-packages/ipykernel/subshell_manager.py", line 227, in _send_on_shell_channel
    assert current_thread().name == SHELL_CHANNEL_THREAD_NAME
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError